language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
install:
- ". ./travis-ci/install-openapi-generator.sh"
- openssl aes-256-cbc -K $encrypted_a4ab3f701f30_key -iv $encrypted_a4ab3f701f30_iv -in ./travis-ci/deploy_keys.tar.enc -out ./travis-ci/deploy_keys.tar -d
- tar xvf ./travis-ci/deploy_keys.tar -C ./travis-ci/
script:
- "/bin/sh ./generate-sdks"
after_success:
- git config --global user.name "Neblio Team"
- git config --global user.email "info@nebl.io"
- "/bin/sh ./travis-ci/push-python-sdk.sh"
- "/bin/sh ./travis-ci/push-javascript-sdk.sh"
- "/bin/sh ./travis-ci/push-csharp-sdk.sh"
- "/bin/sh ./travis-ci/push-java-sdk.sh"
- "/bin/sh ./travis-ci/push-go-sdk.sh"
- "/bin/sh ./travis-ci/push-objc-sdk.sh"
- "/bin/sh ./travis-ci/push-php-sdk.sh"

